version: 2
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Package the library.
          command: dotnet pack --include-symbols --include-source -c Release -o ./nuget
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren
      - run:
          name: Publish to nuget
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren/nuget/
          command: |
            VERSION=$(grep -oP "<Version>(.*)</Version>" ../GlobalX.AspNetCore.Hateoas.Siren.csproj |  cut -d ">" -f 2 | cut -d "<" -f 1)
            echo $VERSION
            dotnet nuget push GlobalX.AspNetCore.Hateoas.Siren.$VERSION.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          context: Keys