version: 2
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: 
          command: dotnet pack --include-symbols --include-source -c Release -o ./nuget
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren
      - run:
          working_directory: src/GlobalX.AspNetCore.Hateoas.Siren/nuget/
          command: dotnet nuget push GlobalX.AspNetCore.Hateoas.Siren.$VERSION.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json